<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-NotificationService.Workers-2b130622-721d-4bb0-bb8e-762b142bc22a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CrossQueue.Hub" Version="1.1.7" />
    <PackageReference Include="CSharpTypes.Extensions" Version="1.0.0" />
	<PackageReference Include="DiagnosKit.Core" Version="2.1.3" />
	<PackageReference Include="DRY.MailJetClient.Library" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
	<PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageReference Include="KwikNesta.Contracts.Core" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
	  <Content Include="wwwroot\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="wwwroot\templates\account-deactivation.html" />
    <None Remove="wwwroot\templates\account-reactivation-notification.html" />
    <None Remove="wwwroot\templates\account-reactivation.html" />
    <None Remove="wwwroot\templates\account-suspension.html" />
    <None Remove="wwwroot\templates\admin-account-reactivation.html" />
    <None Remove="wwwroot\templates\password-reset-notification.html" />
  </ItemGroup>
</Project>